server:
  port: 8080

spring:
  datasource:
    username: root
    password: cthsq30896
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.playback.ru/
      name: PlayBack.ru
    - url: https://nikoartgallery.com/
      name: Nikoartgallery.com
    - url: https://volochek.life/
      name: Volochek.life/
    - url: https://skillbox.ru/
      name: Skillbox.ru


connection-settings:
  userAgent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0
  referer: http://www.yandex.ru